# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/0490898c-c7a9-4ad0-b3cf-5c0dec0c0d9d";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/0490898c-c7a9-4ad0-b3cf-5c0dec0c0d9d";
      fsType = "btrfs";
      options = [ "subvol=@store" ];
    };

  fileSystems."/etc/nixos" =
    { device = "/dev/disk/by-uuid/0490898c-c7a9-4ad0-b3cf-5c0dec0c0d9d";
      fsType = "btrfs";
      options = [ "subvol=@nixos" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-uuid/0490898c-c7a9-4ad0-b3cf-5c0dec0c0d9d";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/a9b20bcb-0904-47a6-97fc-025506452a56"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
